<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: "Lato", sans-serif;
}

.sidenav {
  height: 100%;
  width: 160px;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #111;
  overflow-x: hidden;
  padding-top: 20px;
}

.sidenav a {
  padding: 6px 8px 6px 16px;
  text-decoration: none;
  font-size: 25px;
  color: #818181;
  display: block;
}

.sidenav a:hover {
  color: #f1f1f1;
}

.main {
  margin-left: 160px; /* Same as the width of the sidenav */
  font-size: 18px; 
  padding: 0px 10px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}
</style>
</head>
<body>

<div class="sidenav">
  <a href="/index/index" style="color: white;">Dashboard</a>
  <a href="/users/index" style="color: white;">Users</a>
  <a href="/blog/index" style="color: white;">Blogs</a>
  <a href="/addpost/index" style="color: white;">Add Blog</a>

</div>

<div class="main">
  
<?php


echo $this->tag->linkTo(["signup", "Sign-Up ", 'class' => 'btn btn-primary']);
echo"<h2> Users Record </h2>";
if ($users->count() > 0) {
    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Email</th>
            <th>Role</th>
            <th>Status</th>
            <th colspan="2">Action</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="6">Total Users: <?php echo $users->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php
             foreach ($users as $user) { 
              if($user->role == 'users'){ ?>
            <tr>
                <td><?php echo $user->id; ?></td>
                <td><?php echo $user->username; ?></td>
                <td><?php echo $user->email; ?></td>
                <td><?php echo $user->role; ?></td>
                <td><?php echo $user->status; ?></td>
                <td><?php echo $this->tag->linkTo(["edits/edits/$user->id", "edit"]);?></td>
               <td><?php echo $this->tag->linkTo(["index/delete/$user->id", "delete"]);?></td>

                
            </tr>
        <?php } else{ 
              
        }?>
        <?php }?>
        </tbody>
    </table>
    <?php  echo $this->tag->linkTo(["blog/index", "Go to blog "]);?>
    <?php }?>


</div>
</body>