<?php
?>
<!DOCTYPE html>
<html lang="en">

<head>
	<!-- basic -->
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<!-- mobile metas -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="viewport" content="initial-scale=1, maximum-scale=1">
	<!-- site metas -->
	<title>Pullshoes</title>
	<meta name="keywords" content="">
	<meta name="description" content="">
	<meta name="author" content="">
	<!-- bootstrap css -->
	<link rel="stylesheet" href="../../../public/css2/slick.css">
	<link rel="stylesheet" href="../../../public/css2/animate.min.css">
	<link rel="stylesheet" href="../../../public/css2/jquery-ui.css">
	<link rel="stylesheet" href="../../../public/css2/nice-select.css">
	<link rel="stylesheet" href="../../../public/css2/normalize.css">
	<link rel="stylesheet" href="../../../public/css2/bootstrap.min.css">
	<!-- style css -->
	<link rel="stylesheet" href="../../../public/css2/style2.css">
	<!-- Responsive-->
	<link rel="stylesheet" href="../../../public/css2/responsive.css">
	<!-- fevicon -->
	<link rel="icon" href="../../../public/img2/fevicon.png" type="image/gif" />
	<!-- Scrollbar Custom CSS -->
	<link rel="stylesheet" href="../../../public/css2/jquery.mCustomScrollbar.min.css">
	<!-- Tweaks for older IEs-->
	<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
	<!-- owl stylesheets -->
	<link rel="stylesheet" href="../../../public/css2/owl.carousel.min.css">
	<link rel="stylesheet" href="../../../public/css2/owl.theme.default.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
	<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
	  <style>
		.dropbtn {
			/* background-color: red; */
			color: white;
			padding: 16px;
			font-size: 16px;
			border: none;
		}

		.dropdown {
			position: relative;
			display: inline-block;
		}

		.dropdown-content {
			display: none;
			position: absolute;
			background-color: #f1f1f1;
			min-width: 160px;
			box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
			z-index: 1;
		}

		.dropdown-content a {
			color: black;
			padding: 12px 16px;
			text-decoration: none;
			display: block;
		}

		.dropdown-content a:hover {
			background-color: #ddd;
		}

		.dropdown:hover .dropdown-content {
			display: block;
		}

		.dropdown:hover .dropbtn {
			background-color: #3e8e41;
		}
	</style>
</head>
<!-- body -->
<style>
		.dropbtn {
		
			color: white;
			padding: 16px;
			font-size: 16px;
			border: none;
		}

		.dropdown {
			position: relative;
			display: inline-block;
		}

		.dropdown-content {
			display: none;
			position: absolute;
			background-color: green;
			min-width: 160px;
			box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
			z-index: 1;
		}

		.dropdown-content a {
			color: black;
			padding: 12px 16px;
			text-decoration: none;
			display: block;
		}

		.dropdown-content a:hover {
			background-color: #ddd;
		}

		.dropdown:hover .dropdown-content {
			display: block;
		}

		.dropdown:hover .dropbtn {
			background-color: #3e8e41;
		}
	</style>
</head>
<body class="main-layout">
	<!-- header section start -->
	<div class="header_section header_main">
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="logo"><a href="#"><img src="../../../public/img2/logo.png"></a></div>
				</div>
				<div class="col-sm-9">
					<nav class="navbar navbar-expand-lg navbar-light bg-light">
						<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
							<span class="navbar-toggler-icon"></span>
						</button>
						<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
							<div class="navbar-nav">
								<a class="nav-item nav-link" href="/blog/index">Home</a>
								<a class="nav-item nav-link" href="/blog/collection">Collection</a>
					
									<a class="nav-item nav-link" style="background-color: black;"href="/blog/racingboots">Products</a>
								
						
								<a class="nav-item nav-link" href="/blog/contact">Contact</a>
								<a class="nav-item nav-link" href="/blog/logout">logout</a>
								<a class="nav-item nav-link last" href="#"><img src="../../../public/img2/search_icon.png"></a>
								<a class="nav-item nav-link last" href="contact.html"><img src="../../../public/img2/shop_icon.png"></a>
							</div>
						</div>
					</nav>
				</div>
			</div>
		</div>
		<div class="banner_section">
			<div class="container-fluid">
				<section class="slide-wrapper">
					<div class="container-fluid">
						<div id="myCarousel" class="carousel slide" data-ride="carousel">
							<!-- Indicators -->
							<ol class="carousel-indicators">
								<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
								<li data-target="#myCarousel" data-slide-to="1"></li>
								<li data-target="#myCarousel" data-slide-to="2"></li>
								<li data-target="#myCarousel" data-slide-to="3"></li>
							</ol>

							<!-- Wrapper for slides -->
							<div class="carousel-inner">
								<div class="carousel-item active">
									<div class="row">
										<div class="col-sm-2 padding_0">
											<p class="mens_taital" style="color:red;">Men Shoes</p>
											<div class="page_no" style="color: grey;">0/4</div>
										</div>
										<div class="col-sm-5">
											<div class="banner_taital">
												<h1 class="banner_text">New Running Shoes </h1>
												<h1 class="mens_text"><strong>Men's Like Plex</strong></h1>
												<p class="lorem_text">ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
												<button class="buy_bt">Buy Now</button>
												<button class="more_bt">See More</button>
											</div>
										</div>
										<div class="col-sm-5">
											<div class="shoes_img"><img src="../../../public/img2/running-shoes.png"></div>
										</div>
									</div>
								</div>
								<div class="carousel-item">
									<div class="row">
										<div class="col-sm-2 padding_0">
											<p class="mens_taital" style="color:red;">Men Shoes</p>
											<div class="page_no" style="color: grey;">1/4</div>

										</div>
										<div class="col-sm-5">
											<div class="banner_taital">
												<h1 class="banner_text">New Running Shoes </h1>
												<h1 class="mens_text"><strong>Men's Like Plex</strong></h1>
												<p class="lorem_text">ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
												<button class="buy_bt">Buy Now</button>
												<button class="more_bt">See More</button>
											</div>
										</div>
										<div class="col-sm-5">
											<div class="shoes_img"><img src="../../../public/img2/running-shoes.png"></div>
										</div>
									</div>
								</div>
								<div class="carousel-item">
									<div class="row">
										<div class="col-sm-2 padding_0">
											<p class="mens_taital" style="color:red;">Men Shoes</p>
											<div class="page_no" style="color: grey;">3/4</div>

										</div>
										<div class="col-sm-5">
											<div class="banner_taital">
												<h1 class="banner_text">New Running Shoes </h1>
												<h1 class="mens_text"><strong>Men's Like Plex</strong></h1>
												<p class="lorem_text">ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
												<button class="buy_bt">Buy Now</button>
												<button class="more_bt">See More</button>
											</div>
										</div>
										<div class="col-sm-5">
											<div class="shoes_img"><img src="../../../public/img2/running-shoes.png"></div>
										</div>
									</div>
								</div>
								<div class="carousel-item">
									<div class="row">
										<div class="col-sm-2 padding_0">
											<p class="mens_taital" style="color:red;">Men Shoes</p>
											<div class="page_no" style="color: grey;">4/4</div>

										</div>
										<div class="col-sm-5">
											<div class="banner_taital">
												<h1 class="banner_text">New Running Shoes </h1>
												<h1 class="mens_text"><strong>Men's Like Plex</strong></h1>
												<p class="lorem_text">ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
												<button class="buy_bt">Buy Now</button>
												<button class="more_bt">See More</button>
											</div>
										</div>
										<div class="col-sm-5">
											<div class="shoes_img"><img src="../../../public/img2/running-shoes.png"></div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</section>
			</div>
		</div>
	</div>
	<!-- header section end -->
	<!-- new collection section start -->
	<div class="layout_padding collection_section">
		<div class="container">
			<h1 class="new_text"><strong>New Collection</strong></h1>
			<p class="consectetur_text">consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation</p>
			<div class="collection_section_2">
				<div class="row">
					<div class="col-md-6">
						<div class="about-img">
							<button class="new_bt">New</button>
							<div class="shoes-img"><img src="../../../public/img2/shoes-img1.png"></div>
							<p class="sport_text">Men Sports</p>
							<div class="dolar_text">$<strong style="color: #f12a47;">90</strong> </div>
							<div class="star_icon">
								<ul>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
								</ul>
							</div>
						</div>
						<button class="seemore_bt">See More</button>
					</div>
					<div class="col-md-6">
						<div class="about-img2">
							<div class="shoes-img2"><img src="../../../public/img2/shoes-img2.png"></div>
							<p class="sport_text">Men Sports</p>
							<div class="dolar_text">$<strong style="color: #f12a47;">90</strong> </div>
							<div class="star_icon">
								<ul>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="collection_section">
		<div class="container">
			<h1 class="new_text"><strong>Racing Boots</strong></h1>
			<p class="consectetur_text">consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation</p>
		</div>
	</div>
	<div class="collectipn_section_3 layuot_padding">
		<div class="container">
			<div class="racing_shoes">
				<div class="row">
					<div class="col-md-8">
						<div class="shoes-img3"><img src="../../../public/img2/shoes-img3.png"></div>
					</div>
					<div class="col-md-4">
						<div class="sale_text"><strong>Sale <br><span style="color: #0a0506;">JOGING</span> <br>SHOES</strong></div>
						<div class="number_text"><strong>$ <span style="color: #0a0506">100</span></strong></div>
						<button class="seemore">See More</button>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="collection_section layout_padding">
		<div class="container">
			<h1 class="new_text"><strong>New Arrivals Products</strong></h1>
			<p class="consectetur_text">consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation</p>
		</div>
	</div>
	<!-- new collection section end -->
	<!-- New Arrivals section start -->
	<div class="layout_padding gallery_section">
		<div class="container">
			<div class="row">
				<div class="col-sm-4">
					<div class="best_shoes">
						<p class="best_text">Best Shoes </p>
						<div class="shoes_icon"><img src="../../../public/img2/shoes-img4.png"></div>
						<div class="star_text">
							<div class="left_part">
								<ul>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
								</ul>
							</div>
							<div class="right_part">
								<div class="shoes_price">$ <span style="color: #ff4e5b;">60</span></div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-sm-4">
					<div class="best_shoes">
						<p class="best_text">Best Shoes </p>
						<div class="shoes_icon"><img src="../../../public/img2/shoes-img5.png"></div>
						<div class="star_text">
							<div class="left_part">
								<ul>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
								</ul>
							</div>
							<div class="right_part">
								<div class="shoes_price">$ <span style="color: #ff4e5b;">400</span></div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-sm-4">
					<div class="best_shoes">
						<p class="best_text">Best Shoes </p>
						<div class="shoes_icon"><img src="../../../public/img2/shoes-img6.png"></div>
						<div class="star_text">
							<div class="left_part">
								<ul>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
								</ul>
							</div>
							<div class="right_part">
								<div class="shoes_price">$ <span style="color: #ff4e5b;">50</span></div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-4">
					<div class="best_shoes">
						<p class="best_text">Sports Shoes</p>
						<div class="shoes_icon"><img src="../../../public/img2/shoes-img7.png"></div>
						<div class="star_text">
							<div class="left_part">
								<ul>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
								</ul>
							</div>
							<div class="right_part">
								<div class="shoes_price">$ <span style="color: #ff4e5b;">70</span></div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-sm-4">
					<div class="best_shoes">
						<p class="best_text">Sports Shoes</p>
						<div class="shoes_icon"><img src="../../../public/img2/shoes-img8.png"></div>
						<div class="star_text">
							<div class="left_part">
								<ul>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
								</ul>
							</div>
							<div class="right_part">
								<div class="shoes_price">$ <span style="color: #ff4e5b;">100</span></div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-sm-4">
					<div class="best_shoes">
						<p class="best_text">Sports Shoes</p>
						<div class="shoes_icon"><img src="../../../public/img2/shoes-img9.png"></div>
						<div class="star_text">
							<div class="left_part">
								<ul>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
									<li><a href="#"><img src="../../../public/img2/star-icon.png"></a></li>
								</ul>
							</div>
							<div class="right_part">
								<div class="shoes_price">$ <span style="color: #ff4e5b;">90</span></div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="buy_now_bt">
				<button class="buy_text">Buy Now</button>
			</div>
		</div>
	</div>
	<!-- New Arrivals section end -->
	<!-- contact section start -->
	<div class="layout_padding contact_section">
		<div class="container">
			<h1 class="new_text"><strong>Contact Now</strong></h1>
		</div>
		<div class="container-fluid ram">
			<div class="row">
				<div class="col-md-6">
					<div class="email_box">
						<div class="input_main">
							<div class="container">
								<form action="/action_page.php">
									<div class="form-group">
										<input type="text" class="email-bt" placeholder="Name" name="Name">
									</div>
									<div class="form-group">
										<input type="text" class="email-bt" placeholder="Phone Numbar" name="Name">
									</div>
									<div class="form-group">
										<input type="text" class="email-bt" placeholder="Email" name="Email">
									</div>

									<div class="form-group">
										<textarea class="massage-bt" placeholder="Massage" rows="5" id="comment" name="Massage"></textarea>
									</div>
								</form>
							</div>
							<div class="send_btn">
								<button class="main_bt">Send</button>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-6">
					<div class="image1"><img src="../../../public/img2/shoes-img2.png" alt="shoes" style="opacity: 0.6; width:100%; height:100%;">
						<div class="our_shop">
							<button class="out_shop_bt bg-danger" style="color:azure">Our Shop</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- contact section end -->
	<!-- section footer start -->
	<div class="section_footer">
		<div class="container">
			<div class="mail_section">
				<div class="row">
					<div class="col-sm-6 col-lg-2">
						<div><a href="#"><img src="../../../public/img2/footer-logo.png"></a></div>
					</div>
					<div class="col-sm-6 col-lg-2">
						<div class="footer-logo"><img src="../../../public/img2/phone-icon.png"><span class="map_text">(71) 1234567890</span></div>
					</div>
					<div class="col-sm-6 col-lg-3">
						<div class="footer-logo"><img src="../../../public/img2/email-icon.png"><span class="map_text">Demo@gmail.com</span></div>
					</div>
					<div class="col-sm-6 col-lg-3">
						<div class="social_icon">
							<ul>
								<li><a href="#"><img src="../../../public/img2/fb-icon.png"></a></li>
								<li><a href="#"><img src="../../../public/img2/twitter-icon.png"></a></li>
								<li><a href="#"><img src="../../../public/img2/in-icon.png"></a></li>
								<li><a href="#"><img src="../../../public/img2/google-icon.png"></a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2"></div>
				</div>
			</div>
			<div class="footer_section_2">
				<div class="row">
					<div class="col-sm-4 col-lg-2">
						<p class="dummy_text"> ipsum dolor sit amet, consectetur ipsum dolor sit amet, consectetur ipsum dolor sit amet,</p>
					</div>
					<div class="col-sm-4 col-lg-2">
						<h2 class="shop_text">Address </h2>
						<div class="image-icon"><img src="../../../public/img2/map-icon.png"><span class="pet_text">No 40 Baria Sreet 15/2 NewYork City, NY, United States.</span></div>
					</div>
					<div class="col-sm-4 col-md-6 col-lg-3">
						<h2 class="shop_text">Our Company </h2>
						<div class="delivery_text">
							<ul>
								<li>Delivery</li>
								<li>Legal Notice</li>
								<li>About us</li>
								<li>Secure payment</li>
								<li>Contact us</li>
							</ul>
						</div>
					</div>
					<div class="col-sm-6 col-lg-3">
						<h2 class="adderess_text">Products</h2>
						<div class="delivery_text">
							<ul>
								<li>Prices drop</li>
								<li>New products</li>
								<li>Best sales</li>
								<li>Contact us</li>
								<li>Sitemap</li>
							</ul>
						</div>
					</div>
					<div class="col-sm-6 col-lg-2">
						<h2 class="adderess_text">Newsletter</h2>
						<div class="form-group">
							<input type="text" class="enter_email" placeholder="Enter Your email" name="Name">
						</div>
						<button class="subscribr_bt">Subscribe</button>
					</div>
				</div>
			</div>
		</div>
	</div>
	</div>
	<!-- section footer end -->
	<div class="copyright">2019 All Rights Reserved. <a href="https://html.design">Free html Templates</a></div>


	<!-- Javascript files-->
	<script src="../../../public/js2/jquery.min.js"></script>
	<script src="../../../public/js2/popper.min.js"></script>
	<script src="../../../public/js2/bootstrap.bundle.min.js"></script>
	<script src="../../../public/js2/jquery-3.0.0.min.js"></script>
	<script src="../../../public/js2/plugin.js"></script>
	<!-- sidebar -->
	<script src="../../../public/js2/jquery.mCustomScrollbar.concat.min.js"></script>
	<script src="../../../public/js2/custom.js"></script>
	<!-- javascript -->
	<script src="../../../public/js2/owl.carousel.js"></script>
	<script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
	<script>
		$(document).ready(function() {
					$(".fancybox").fancybox({
						openEffect: "none",
						closeEffect: "none"
					});


					$('#myCarousel').carousel({
						interval: false
					});

					//scroll slides on swipe for touch enabled devices

					$("#myCarousel").on("touchstart", function(event) {

						var yClick = event.originalEvent.touches[0].pageY;
						$(this).one("touchmove", function(event) {

							var yMove = event.originalEvent.touches[0].pageY;
							if (Math.floor(yClick - yMove) > 1) {
								$(".carousel").carousel('next');
							} else if (Math.floor(yClick - yMove) < -1) {
								$(".carousel").carousel('prev');
							}
						});
						$(".carousel").on("touchend", function() {
							$(this).off("touchmove");
						});
					});
	</script>
</body>

</html>