<h2>Users Edit Records</h2>

<?php echo $this->tag->form("index/edits/$userid") ?>
 <?php  echo "Usersid:" .$userid; ?>
    <p>
        <label for="name">Name</label>
        <?php echo $this->tag->textField("username"); ?>
    </p>

    <p>
        <label for="email">E-Mail</label>
        <?php echo $this->tag->textField("email"); ?>
    </p>
    <p>
        <label for="email">Password</label>
        <?php echo $this->tag->textField("password"); ?>
    </p>
   

    <p>
        <?php echo $this->tag->submitButton("submit"); ?>
    </p>

</form>
