<?php
echo $this->tag->linkTo(["addpost/createpost", "create", 'class' => 'btn btn-primary']);
echo"<h2> Blogs </h2>";
if ($users->count() > 0) {
    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>Id</th>
            <th>UserId</th>
            <th>UserName</th>
            <th>Title</th>
            <th>Content</th>
            <th colspan="2">Action</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="6">Total Blogs: <?php echo $users->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($users as $user) { ?>
            <tr>
                <td><?php echo $user->id; ?></td>
                <td><?php echo $user->userid; ?></td>
                <td><?php echo $user->username; ?></td>
                <td><?php echo $user->title; ?></td>
                <td><?php echo $user->content; ?></td>
                <td><?php echo $this->tag->linkTo(["addpost/viewpost/$user->id", "view", 'class' => 'btn btn-primary']);?></td>
                <td><?php echo $this->tag->linkTo(["addpost/deleteposts/$user->id", "delete", 'class' => 'btn btn-danger']);?></td>
                
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php  echo $this->tag->linkTo(["blog/index", "Go to blog "]);?>
    <?php }?>
    